### ISSUE TITLE
Login 작업을 위한 기초 세팅

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#11]
## 💡 요약

앞으로 카카오, 애플 Login 작업을 위한 기초 세팅입니다.

## 💻 Todo

- [x] SingInViewController에 임시버튼 추가 
- [x] Presentable을 통해 SignInInteractor와 SinginViewController 연결
- [x] Network Layer 추가
