### ISSUE TITLE
강아지 성격 바텀 시트 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#135]
## 💡 요약

강아지 성격 바텀 시트 구현입니다.

## 💻 Todo

- [x] 강아지 바텀 시트 구현
- [x] Presentation 내에 Core 생성
- [x] 데이터 피커 위치 변경
