### ISSUE TITLE
유저 API, Repository 수정

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#142]
## 💡 요약

유저 API, Repository 수정입니다.

## 💻 Todo

- [ ] 유저 DTO 수정
- [ ] 유저 API 수정
- [ ] 유저 Repository 수정 
- [ ] OnBoardingUseCase 유저관련 유즈케이스 작성 
- [ ] OnBoarding-UseSetting 리블렛 수정
