### ISSUE TITLE
순환 참조 해결 및 Profile UI 수정

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#28]
## 💡 요약

기존 Lazy var로 인한 순환 참조 해결과 
Profile 수정된 UI 적용입니다.

## 💻 Todo

- [ ] Profile UI 수정
- [ ] OnBoarding 주소 변경 Layout 수정
- [ ] Lazy var로 인한 순환 참조 수정
