### ISSUE TITLE
강아지 수정 Interactor 작업

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#51]
## 💡 요약

강아지 수정 Interactor Logic 작업입니다.

## 💻 Todo

- [x] 강아지 수정 UI 리팩토링
- [x] 강아지 수정 ViewWillAppear시 바인딩
- [x] 강아지 Entity 수정
- [x] 강아지 Update Use Case, Repository
- [x] 강아지 Update DTO및 API
