### ISSUE TITLE
강아지 프로필 추가 Interactor 로직 작업

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#73]
## 💡 요약

강아지 추가 Interactor 로직 작업.

## 💻 Todo

- [x] 강아지 추가 DTO작업
- [x] 강아지 추가 UseCase 작성
- [x] 강아지 추가 Repository 작업
- [x] Interactor와 연결작업
