### ISSUE TITLE
키보드 버그 수정 및 스와이프 뒤로가기 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#82]
## 💡 요약

키보드 버그 수정 및 스와이프 뒤로가기 구현
## 💻 Todo

- [x] 유저 프로필 수정 키보드 안내려가는 버그 수정
- [x] 스와이프로 뒤로가는 기능 구현
- [x] 유저 수정 확인 버튼 로직 구현 
- [x] 유저 수정 warning 로직 구현
