### ISSUE TITLE
SwiftLint 설정

### ISSUE THREAD

**Issue by klmyoungyun** [WalkingDogWithFriends/GaeManDa#9]
## 💡 요약

SwiftLint 설정

## 💻 Todo

- [x] swiftlint 설정
- [x] 프로젝트에 린트 적용
- [x] tuist에 린트 적용
- [x] 린트에 맞지 않는 코드 있을 시 커밋 막는 스크립트 작성
