### ISSUE TITLE
이미지 선택 기능 적용

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#94]
## 💡 요약

이미지 선택 기능 적용이슈입니다. 

## 💻 Todo

- [ ] 새로운 강아지 추가 이미지 선택 기능 적용 
- [ ] 유저 프로필 수정 이미지 선택 기능 적용
- [ ] 강아지 프로필 수정 이미지 선택 기능 적용
- [ ] 강아지 프로필 수정 리팩토링
