### ISSUE TITLE
리블렛 네이밍 수정

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [WalkingDogWithFriends/GaeManDa#98]
## 💡 요약

리블렛 네이밍 수정입니다.

## 💻 Todo

- [x] `DogsOnAround`에서 `GmdMap`으로 수정
- [x] `UserProfile`에서 `GmdProfile`으로 수정
- [x] `DataMapper` 위치 수정
